[env:E22_XML-DevKitC]
extends = esp32_classic
board = az-delivery-devkit-v4
monitor_dtr = 0
monitor_rts = 0

lib_ignore =
	AceButton
	Adafruit TCA8418
	epdiy
	ESP32-audioI2S
	lvgl
	SensorLibTDECKpro
	TFT_eSPI
	TinyGSM
	XPowersLib
	
lib_deps =
	${libs.lib_deps}
	${esp32libs.lib_deps}
	plerup/EspSoftwareSerial@^8.2.0

	; Display Library
	olikraus/U8g2@^2.36.5
	
build_flags = 
	${esp32.build_flags}
	${common.build_flags}
	-D BOARD_E22="az-delivery-devkit-v4"
	-I variants/${this.__env__}
	-D DISABLE_NET_CONSOLE
	-D MC_DIAG=0
	-D MC_INJECT_HOOKS=0