#!/bin/sh
# Gate for the golden-capture tooling. Every tool here carries its own tests
# against real repository fixtures, not against invented input -- run them all
# before trusting a capture produced with them.
#
#   sh test/golden/selftest.sh
set -e
cd "$(dirname "$0")/../.."

python3 test/golden/mc_frame.py
python3 test/golden/normalize.py --self-test
python3 test/golden/corpus_lint.py --self-test
python3 test/golden/extract_commands.py --self-test
python3 test/golden/build_corpus.py --self-test
python3 test/golden/backup_nodes.py --self-test
python3 test/golden/backup_nodes.py --verify-masked
python3 tools/bench/ble_golden.py --self-test
python3 test/golden/command_name_scan.py --self-test
python3 test/golden/compare_udp.py --self-test
python3 test/golden/compare_extudp.py --self-test
python3 test/golden/radio_units_lint.py --self-test
python3 test/golden/radio_units_lint.py
python3 test/golden/nano_printf_lint.py --self-test
python3 test/golden/nano_printf_lint.py
python3 test/golden/twin_stub_lint.py --self-test
python3 test/golden/twin_stub_lint.py
python3 test/golden/carve_extern_lint.py --self-test
python3 test/golden/carve_extern_lint.py
python3 test/golden/command_ladder_lint.py --self-test
python3 test/golden/command_ladder_lint.py
python3 test/golden/settings_layout_lint.py --self-test
python3 test/golden/settings_layout_lint.py
# W3 step 1: both settings gates stand BEFORE the migration rewrites this
# code, not after. settings_persist_lint is currently clean -- DR-13's
# failure mode (a field in the X() table with no preferences.put* call, so
# the node silently forgets it) is not present today; the gate exists to
# keep it that way while W3 replaces 266 hand-written NVS calls with a
# schema walk. Mutation-verified: deleting one putInt() makes it fail.
python3 test/golden/settings_persist_lint.py --self-test
python3 test/golden/settings_persist_lint.py
# W3 step 2: the schema gate. settings_schema.{h,cpp} builds the persistence
# descriptor table by expanding config_json.h's CFG_FIELD_LIST plus the
# persist-only list, so the two must not drift from each other or from the
# D1-04 field triage. This gate holds four properties the table cannot assert
# about itself: every PERSIST field is covered or explicitly exempted, no
# RUNTIME field slipped in, no key or member is duplicated, and triage
# disagreement (a) stays at zero. The 10 exemptions are pinned in-script --
# the 8 counter/sensor fields and the 2 Arduino String members.
python3 test/golden/settings_schema_lint.py --self-test
python3 test/golden/settings_schema_lint.py
python3 test/golden/variant_macros_lint.py --self-test
python3 test/golden/variant_macros_lint.py
python3 test/golden/twin_diff.py --self-test
# The U1/U2 twin-diff artefacts (testplan 4.4/9.1). The pass condition is
# NOT an empty diff -- the platform drift is expected -- it is that the
# committed before-diff still matches what the current dumps produce. A
# block flipping agree<->differ fails here, including a drift row that was
# deliberately FIXED: that has to be acknowledged by regenerating, not
# absorbed silently. Dumps are regenerated by the twin suites themselves
# (pio test -e native_udp_frame_twin / native_udp_send_twin).
python3 test/golden/twin_diff.py --check test/golden/native/u1-esp32.txt test/golden/native/u1-nrf52.txt test/golden/native/u1-twin-diff-before.txt
python3 test/golden/twin_diff.py --check test/golden/native/u2-esp32.txt test/golden/native/u2-nrf52.txt test/golden/native/u2-twin-diff-before.txt
python3 test/golden/drift_matrix_lint.py --self-test
# --phase implementation is TEMPORARY. The M2 review happened on 2026-09-12 and
# filled all 29 verdicts, so the empty-verdict check is now enforced HARD and
# --phase pre-review is obsolete. What this phase still downgrades is the
# asserting_test column: 10 rows are decided but not yet implemented, so the
# test that would fail does not exist yet. Drop the flag -- run this line with
# no --phase at all -- once the unification waves have written them. A phase
# flag left in place after its window has passed is how a requirement quietly
# expires, which is why the script prints the count on every run.
python3 test/golden/drift_matrix_lint.py --phase implementation
# The W3 upgrade proof's instrument. Not a golden gate -- it is pointed at real
# hardware by a human after the nRF52 cutover, comparing a fresh config export
# against the baselines in docs/bench/w3-baseline/ that were captured while the
# nodes still ran a 20260724 image. Its self-test runs here so it cannot rot
# between now and the bench run that depends on it.
python3 tools/bench/w3_upgrade_check.py --self-test
python3 test/golden/verify_captures.py
python3 test/golden/corpus_lint.py test/golden/corpus/
python3 -m unittest discover tools/mock 2>&1 | tail -3
