#!/usr/bin/env python3
"""Cross-variant consistency gate for `variants/*/configuration.h` macros.

Every board defines the same family of configuration macros in its own
`configuration.h`. They drift silently, because nothing else compares them:
a macro added for one board goes quietly missing on another, or -- worse --
the same macro name means a different quantity per platform. Both shapes are
real, not hypothetical:

  OPT-D14  LORA_BANDWIDTH is 250 (kHz) on every ESP32 variant but 1 (a
           bandwidth INDEX, not a kHz value) on the three nRF52 variants
           (wiscore_rak4631, heltec_t114, t_echo) -- same macro name, two
           different units, sharing nothing but the spelling.

That is not academic: RF-04 (docs/BACKLOG.md, commit 136dacdd) happened
because `--txfreq`'s guard-band arithmetic fed the raw `LORA_BANDWIDTH`
macro straight into a calculation that assumed kHz. On ESP32 that was merely
imprecise; on nRF52 it silently computed from a bandwidth index instead of a
bandwidth, and the resulting guard window was wrong by two different wrong
amounts depending on which platform built it. A tool that had already been
diffing `LORA_BANDWIDTH`'s value across platforms would have made that
inconsistency visible before it reached call-site arithmetic, which is what
this gate is for.

This is a CHARACTERIZATION gate, not a judgement one: it records what every
variant's configuration.h currently defines, and fails when that recorded
table changes. It does not decide which value is "right" -- that is the
drift matrix's job elsewhere -- it only makes sure nobody changes the macro
landscape without a human looking at the diff. Deliberate changes are
regenerated by copy-pasting the table this script prints (same convention as
test/test_country_twin/test_country_twin.cpp) into the committed baseline.

WHAT IS PARSED. Every `variants/*/configuration.h` (`t5_epaper` has none and
is skipped by the glob itself, not by a special case). Block comments
(`/* ... */`, single- or multi-line) are stripped from the whole file first,
then each remaining line is matched against `#define NAME [VALUE]` with any
trailing `//` comment removed. A macro defined more than once in the same
file (real cases exist, e.g. a value repeated verbatim, or one conditionally
overridden inside an `#ifdef` block) resolves to whatever the last matching
line in the file says -- this script does not evaluate `#ifdef`/`#endif`,
so it agrees with the compiler only when at most one branch is ever taken in
a real build. `#undef` removes a macro already collected in the same file.
A flag macro (`#define OLED` with no value) is recorded with an empty value,
which is still a distinct fact from "not defined at all".

WHAT COUNTS AS nRF52. Not a hardcoded board list: a variant is nRF52 when
its OWN `variants/<name>/platformio.ini` extends `nrf52_base` (the shared
section in the root `platformio.ini` that supplies `-D BOARD_RAK4630`, and
which `heltec_t114` and `t_echo` inherit deliberately -- see the comment
above `[nrf52_base]` there). Verified by hand against every variant before
writing this: exactly `wiscore_rak4631`, `heltec_t114` and `t_echo` extend
it; nothing else does. `BOARD_RAK4630` itself is a build flag the root
`platformio.ini` supplies, not something any `configuration.h` defines, so
grepping variant sources for the macro name would silently find only
`heltec_t114` (which does `#define USE_HELTEC_T114`) and `t_echo` (whose OWN
`-D BOARD_T_ECHO` lives in its `platformio.ini`) and miss
`wiscore_rak4631` entirely -- the `extends` check is the one signal that is
actually present, per-variant, in a file this tool is allowed to read.

CLASSIFICATION, printed and checked against the baseline:
  - common core: macros every parsed variant defines (any value)
  - suspicious (missing from exactly 1 or 2 variants): the likely-oversight
    class -- present almost everywhere, absent on a small minority
  - ESP32-vs-nRF52 value split: macros defined in at least one variant of
    EACH group, where the two groups' value sets are completely disjoint
    (no ESP32 variant's value equals any nRF52 variant's value) -- the
    LORA_BANDWIDTH shape. A partial overlap does not qualify; this is a
    deliberately narrow, mechanical definition so the check stays a
    characterization, not a judgement call about which values "should"
    agree.

  python3 test/golden/variant_macros_lint.py [--self-test]

Exit 0 when the table matches the committed baseline, 1 on any drift
(including a baseline that does not exist yet -- copy the printed table into
it) and 1 if the parse yields zero variants or zero macros, which means the
extraction pattern stopped matching and every downstream conclusion would be
a false "clean".
"""
import argparse
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

ROOT = Path(__file__).resolve().parents[2]
BASELINE = ROOT / "test/golden/native/variant-macros.txt"

BLOCK_COMMENT = re.compile(r"/\*.*?\*/", re.S)
DEFINE = re.compile(r"^\s*#\s*define\s+(\w+)(?:[ \t]+(.*))?$")
UNDEF = re.compile(r"^\s*#\s*undef\s+(\w+)")
EXTENDS_NRF52 = re.compile(r"^\s*extends\s*=\s*nrf52_base\s*$", re.M)


def parse_configuration_h(path: Path) -> Dict[str, str]:
    """name -> value for every macro this file's configuration.h defines,
    last definition in the file winning (see module docstring)."""
    text = BLOCK_COMMENT.sub("", path.read_text(errors="replace"))
    macros: Dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.split("//", 1)[0]
        m = UNDEF.match(line)
        if m:
            macros.pop(m.group(1), None)
            continue
        m = DEFINE.match(line)
        if not m:
            continue
        name = m.group(1)
        value = " ".join((m.group(2) or "").split())
        macros[name] = value
    return macros


def is_nrf52(variant_dir: Path) -> bool:
    ini = variant_dir / "platformio.ini"
    if not ini.exists():
        return False
    return bool(EXTENDS_NRF52.search(ini.read_text(errors="replace")))


def collect(root: Path = ROOT) -> Tuple[Dict[str, Dict[str, str]], Dict[str, bool]]:
    """variant name -> {macro: value}, and variant name -> is_nrf52."""
    variants: Dict[str, Dict[str, str]] = {}
    group: Dict[str, bool] = {}
    for cfg in sorted(root.glob("variants/*/configuration.h")):
        name = cfg.parent.name
        variants[name] = parse_configuration_h(cfg)
        group[name] = is_nrf52(cfg.parent)
    return variants, group


def build_table(variants: Dict[str, Dict[str, str]],
                 group: Dict[str, bool]) -> Tuple[List[str], Dict[str, object]]:
    """Render the sorted, stable table plus the three classification lists.

    Returns (lines, report) where report has keys "common", "suspicious",
    "split" for use by both the printer and the self-test.
    """
    names = sorted(variants)
    all_macros = sorted({m for macros in variants.values() for m in macros})

    lines: List[str] = []
    common: List[str] = []
    suspicious: List[Tuple[str, List[str]]] = []
    split: List[Tuple[str, Set[str], Set[str]]] = []

    for macro in all_macros:
        defining = [n for n in names if macro in variants[n]]
        missing = [n for n in names if n not in defining]
        for n in defining:
            lines.append(f"{macro}={variants[n][macro]} [{n}]")

        if not missing:
            common.append(macro)
        elif 1 <= len(missing) <= 2:
            suspicious.append((macro, missing))

        esp_vals = {variants[n][macro] for n in defining if not group[n]}
        nrf_vals = {variants[n][macro] for n in defining if group[n]}
        if esp_vals and nrf_vals and esp_vals.isdisjoint(nrf_vals):
            split.append((macro, esp_vals, nrf_vals))

    report = {"common": common, "suspicious": suspicious, "split": split,
              "variants": names, "macros": all_macros}
    return lines, report


def format_report(report: Dict[str, object]) -> str:
    out = []
    out.append(f"{len(report['variants'])} variant(s), "
                f"{len(report['macros'])} distinct macro(s)")
    out.append(f"common core (defined by every variant): {len(report['common'])}")
    susp = report["suspicious"]
    out.append(f"suspicious (missing from 1-2 variants): {len(susp)}")
    for macro, missing in susp:
        out.append(f"  {macro}: missing from {', '.join(missing)}")
    spl = report["split"]
    out.append(f"ESP32-vs-nRF52 value split: {len(spl)}")
    for macro, esp_vals, nrf_vals in spl:
        out.append(f"  {macro}: esp32={sorted(esp_vals)} nrf52={sorted(nrf_vals)}")
    return "\n".join(out)


def render_baseline(lines: List[str]) -> str:
    return "\n".join(lines) + "\n"


def check(root: Path = ROOT,
          baseline: Path = BASELINE) -> Tuple[int, str]:
    """Returns (exit_code, message). message always includes the table and
    classification so a deliberate change is a copy-paste, per house style."""
    variants, group = collect(root)
    if not variants:
        return 1, "FATAL: zero variants parsed -- the glob or the parser stopped matching"
    lines, report = build_table(variants, group)
    if not report["macros"]:
        return 1, "FATAL: zero macros parsed -- the #define pattern stopped matching"

    table = render_baseline(lines)
    summary = format_report(report)

    if not baseline.exists():
        return 1, (f"no committed baseline at {baseline} -- copy the table "
                    f"below into it\n\n--- table ---\n{table}--- end table ---\n\n{summary}")

    committed = baseline.read_text()
    if committed != table:
        return 1, (f"DRIFT from {baseline} -- regenerate by copy-pasting the "
                    f"table below\n\n--- table ---\n{table}--- end table ---\n\n{summary}")

    return 0, f"variant macro table matches {baseline}\n\n{summary}"


def self_test() -> int:
    import shutil
    import tempfile
    ok = True

    def report(name: str, good: bool) -> None:
        nonlocal ok
        print(f"  {'ok ' if good else 'FAIL'} {name}")
        ok = ok and good

    def write_variant(root: Path, name: str, cfg_body: str, nrf52: bool) -> None:
        d = root / "variants" / name
        d.mkdir(parents=True)
        (d / "configuration.h").write_text(cfg_body)
        ini = ("[env:%s]\nextends = nrf52_base\nboard = x\n" % name if nrf52
               else "[env:%s]\nextends = esp32\nboard = x\n" % name)
        (d / "platformio.ini").write_text(ini)

    # --- case 1: all variants agree -> clean table, no suspicious/split ---
    with tempfile.TemporaryDirectory() as d:
        root = Path(d)
        write_variant(root, "espA", "#define LORA_BANDWIDTH 250\n#define COMMON 1\n", False)
        write_variant(root, "espB", "#define LORA_BANDWIDTH 250\n#define COMMON 1\n", False)
        write_variant(root, "nrfA", "#define LORA_BANDWIDTH 250\n#define COMMON 1\n", True)
        variants, group = collect(root)
        _, r = build_table(variants, group)
        report("all agree: LORA_BANDWIDTH is common core, no split",
               "LORA_BANDWIDTH" in r["common"] and not r["split"] and not r["suspicious"])

    # --- case 2: one variant missing a macro -> suspicious class ---
    with tempfile.TemporaryDirectory() as d:
        root = Path(d)
        write_variant(root, "espA", "#define COMMON 1\n#define ONLY_TWO 5\n", False)
        write_variant(root, "espB", "#define COMMON 1\n#define ONLY_TWO 5\n", False)
        write_variant(root, "espC", "#define COMMON 1\n", False)
        variants, group = collect(root)
        _, r = build_table(variants, group)
        susp_names = [m for m, _ in r["suspicious"]]
        report("one variant missing a macro -> reported suspicious, not common",
               "ONLY_TWO" in susp_names and "ONLY_TWO" not in r["common"]
               and "COMMON" in r["common"])

    # --- case 3: nRF52-group value differs -> split class, the OPT-D14 shape ---
    with tempfile.TemporaryDirectory() as d:
        root = Path(d)
        write_variant(root, "espA", "#define LORA_BANDWIDTH 250\n", False)
        write_variant(root, "espB", "#define LORA_BANDWIDTH 250\n", False)
        write_variant(root, "nrfA", "#define LORA_BANDWIDTH 1\n", True)
        write_variant(root, "nrfB", "#define LORA_BANDWIDTH 1\n", True)
        variants, group = collect(root)
        _, r = build_table(variants, group)
        split_names = [m for m, _, _ in r["split"]]
        report("nRF52 value differs from ESP32 value -> reported in split class",
               "LORA_BANDWIDTH" in split_names)
        # and a partial overlap must NOT qualify (deliberately narrow rule)
        write_variant(root, "nrfC", "#define LORA_BANDWIDTH 250\n", True)
        variants, group = collect(root)
        _, r2 = build_table(variants, group)
        split_names2 = [m for m, _, _ in r2["split"]]
        report("partial overlap between groups does not count as a split",
               "LORA_BANDWIDTH" not in split_names2)

    # --- case 4: the parser matching nothing is fatal ---
    with tempfile.TemporaryDirectory() as d:
        root = Path(d)
        code, msg = check(root)
        report("zero variants parsed -> exit 1, fatal message",
               code == 1 and "zero variants" in msg)
        write_variant(root, "espA", "// nothing but a comment, no #define at all\n", False)
        code, msg = check(root)
        report("variants present but zero macros parsed -> exit 1, fatal message",
               code == 1 and "zero macros" in msg)

    # --- case 5: baseline mismatch -> exit 1; matching baseline -> exit 0 ---
    with tempfile.TemporaryDirectory() as d:
        root = Path(d)
        write_variant(root, "espA", "#define COMMON 1\n", False)
        write_variant(root, "nrfA", "#define COMMON 1\n", True)
        baseline = root / "baseline.txt"
        code, msg = check(root, baseline)
        report("no baseline file yet -> exit 1", code == 1 and str(baseline) in msg)
        variants, group = collect(root)
        lines, _ = build_table(variants, group)
        baseline.write_text(render_baseline(lines))
        code, msg = check(root, baseline)
        report("matching baseline -> exit 0", code == 0)
        baseline.write_text("DELIBERATELY WRONG\n")
        code, msg = check(root, baseline)
        report("mismatched baseline -> exit 1, table printed for copy-paste",
               code == 1 and "--- table ---" in msg)

    # --- self-contained proof this is "live": drift on the real tree ---
    with tempfile.TemporaryDirectory() as d:
        root = Path(d)
        shutil.copytree(ROOT / "variants", root / "variants")
        variants, group = collect(root)
        lines, _ = build_table(variants, group)
        baseline = root / "baseline.txt"
        baseline.write_text(render_baseline(lines))
        code, _ = check(root, baseline)
        report("real variants/ tree, freshly generated baseline -> exit 0", code == 0)
        # remove one macro from one real variant's configuration.h and prove
        # the gate now fails against the same baseline
        victim = sorted((root / "variants").glob("*/configuration.h"))[0]
        text = victim.read_text()
        removed = re.sub(r"^\s*#\s*define\s+LORA_SF\b.*$", "", text,
                         count=1, flags=re.M)
        report("setup: a real #define line was actually removed",
               removed != text)
        victim.write_text(removed)
        code, msg = check(root, baseline)
        report("a macro removed from one real variant -> drift, exit 1",
               code == 1 and "DRIFT" in msg)

    return 0 if ok else 1


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args()

    if args.self_test:
        return self_test()

    code, msg = check()
    print(msg)
    return code


if __name__ == "__main__":
    sys.exit(main())
