#!/usr/bin/env python3
"""
remote_cmd.py - build and verify RM1 remote-management command DMs (issue #1189).

Reference implementation of the wire format in
docs/concept-open-issues-20261004.md section 6.2. The firmware C++ host test
loads tools/tests/remote_cmd_vectors.json (generated by this file) and must
reproduce every tag.

Wire format:
    command  RM1 <ctr> <cmd>[ <args>] <tag>
    reply    RM1 <ctr> ok <status> <tag>   |   RM1 <ctr> err <reason> <tag>

    K         = SHA-256(passwd with trailing spaces stripped)            32 bytes
    canonical = "RM1|" + dst + "|" + src + "|" + ctr + "|" + cmd[ + " " + args]
    tag       = first 8 bytes of HMAC-SHA256(K, canonical), 16 lower-case hex
    reply tag = same over "RM1R|" + dst + "|" + src + "|" + ctr + "|" + result
                (dst = managed node, src = sender, as in the command)

Usage:
    remote_cmd.py --dst DK5EN-90 --src DK5EN-1 --passwd SECRET --ctr 42 reboot
    remote_cmd.py --dst DK5EN-90 --src DK5EN-1 --passwd SECRET --ctr 43 txpower 2
    remote_cmd.py --dst DK5EN-90 --src DK5EN-1 --passwd SECRET sync
    remote_cmd.py --dst DK5EN-90 --src DK5EN-1 --passwd SECRET --verify "RM1 42 ok rebooting <tag>"

Default is print-only. With --send-host <ip> the DM text is sent through the net
console (TCP 2323) of the SENDER node, as the direct message
`::{<DST>}<dm text>` (the console's user-message form; see
tools/bench/tdeck_harness.py). Never a group, never a broadcast.

Requires: Python 3.8+, stdlib only.
"""

from __future__ import annotations

import argparse
import hashlib
import hmac
import json
import os
import re
import socket
import sys
import time
from typing import Any, Dict, List, Optional

PROTO = "RM1"
CTR_MAX = 0xFFFFFFFF
PASSWD_MAX = 14  # node_passwd is char[15]
TAG_HEX_LEN = 16  # 8 bytes

# cmd -> argument shape. None = no args, tuple = fixed set of allowed arg strings,
# "int" = single unsigned decimal, "out" = "<a0..a7|b0..b7> <on|off>"
# (MCP23017 pin, the firmware's `--setout` form).
ALLOWLIST: Dict[str, Any] = {
    "reboot": None,
    "status": None,
    "sendpos": None,
    "sendtrack": None,
    "gps": ("on", "off"),
    "track": ("on", "off"),
    "display": ("on", "off"),
    "gateway": ("on", "off"),
    "mesh": ("on", "off"),
    "txpower": "int",
    "setout": "out",
    "sync": None,
}

# Hard-blocked whatever the tag (6.4). Checked before the allowlist so the
# refusal names the reason.
BLOCKED_CMDS = frozenset(
    {
        "cleanflash", "ota-update", "dfu", "deepsleep", "setcall", "passwd",
        "webpwd", "btcode", "setssid", "setpwd", "wifiset", "updrepo",
        "updchan", "autoupdate", "rm", "stor",
    }
)
BLOCKED_CHARS = ("--", ";", "{", "%")

_INT_RE = re.compile(r"^(0|[1-9][0-9]{0,2})$")
_OUT_RE = re.compile(r"[ab][0-7] (on|off)")
_CALL_RE = re.compile(r"^[A-Z0-9/]{2,12}(-[0-9]{1,2})?$")   # upper case: the node binds its configured call
_SEND_CALL_RE = re.compile(r"^[A-Z0-9/]{2,12}-[0-9]{1,2}$")
_TAG_RE = re.compile(r"^[0-9a-f]{16}$")


class RmError(ValueError):
    """A command or reply was refused (allowlist, range or format)."""


# ---------------------------------------------------------------------------
# crypto
# ---------------------------------------------------------------------------

def hmac_sha256(key: bytes, msg: bytes) -> bytes:
    """HMAC-SHA256 (RFC 2104); the one primitive every tag goes through."""
    return hmac.new(key, msg, hashlib.sha256).digest()


def derive_key(passwd: str) -> bytes:
    """K = SHA-256(passwd with trailing spaces stripped), 32 bytes."""
    p = passwd.rstrip(" ")
    if not p:
        raise RmError("empty passwd")
    raw = p.encode("utf-8")
    if len(passwd.rstrip(" ")) > PASSWD_MAX:
        raise RmError("passwd longer than %d characters" % PASSWD_MAX)
    return hashlib.sha256(raw).digest()


def tag(key: bytes, canonical_text: str) -> str:
    """First 8 bytes of HMAC-SHA256(key, canonical_text) as 16 lower-case hex chars."""
    return hmac_sha256(key, canonical_text.encode("utf-8")).hex()[:TAG_HEX_LEN]


# ---------------------------------------------------------------------------
# validation
# ---------------------------------------------------------------------------

def _check_call(name: str, call: str) -> None:
    if not isinstance(call, str) or not _CALL_RE.fullmatch(call):
        raise RmError("bad %s call %r" % (name, call))


def _check_ctr(ctr: int) -> None:
    if isinstance(ctr, bool) or not isinstance(ctr, int):
        raise RmError("ctr must be an integer")
    if ctr < 0 or ctr > CTR_MAX:
        raise RmError("ctr out of range 0..%d" % CTR_MAX)


def validate_command(cmd: str, args: str, ctr: int) -> None:
    """Raise RmError unless (cmd, args, ctr) is an allowlisted RM1 command."""
    _check_ctr(ctr)
    if not isinstance(cmd, str) or not isinstance(args, str):
        raise RmError("cmd and args must be strings")
    text = cmd + (" " + args if args else "")
    for bad in BLOCKED_CHARS:
        if bad in text:
            raise RmError("blocked sequence %r" % bad)
    if cmd in BLOCKED_CMDS:
        raise RmError("command %r is hard-blocked" % cmd)
    if not text.isascii() or not text.isprintable():
        raise RmError("non-printable or non-ASCII text")
    if text != text.lower():
        raise RmError("cmd/args must be lower case")
    if "  " in text or text != text.strip():
        raise RmError("single spaces only, no leading/trailing space")
    if cmd not in ALLOWLIST:
        raise RmError("command %r not on the allowlist" % cmd)

    shape = ALLOWLIST[cmd]
    if shape is None:
        if args:
            raise RmError("%s takes no arguments" % cmd)
    elif shape == "int":
        if not _INT_RE.fullmatch(args):
            raise RmError("%s needs one unsigned integer (0..999)" % cmd)
    elif shape == "out":
        if not _OUT_RE.fullmatch(args):
            raise RmError("setout needs '<a0..a7|b0..b7> <on|off>'")
    elif args not in shape:
        raise RmError("%s needs one of %s" % (cmd, "|".join(shape)))

    if cmd == "sync":
        if ctr != 0:
            raise RmError("sync uses ctr 0")
    elif ctr < 1:
        raise RmError("ctr 0 is reserved for sync")


# ---------------------------------------------------------------------------
# command
# ---------------------------------------------------------------------------

def canonical(dst: str, src: str, ctr: int, cmd: str, args: str = "") -> str:
    """Canonical string a command tag is computed over."""
    return "%s|%s|%s|%d|%s%s" % (PROTO, dst, src, ctr, cmd, " " + args if args else "")


def build_command(
    dst: str, src: str, ctr: int, cmd: str, args: str, passwd: str
) -> str:
    """Return the DM text `RM1 <ctr> <cmd>[ <args>] <tag>`; refuse anything off-list."""
    _check_call("dst", dst)
    _check_call("src", src)
    validate_command(cmd, args, ctr)
    key = derive_key(passwd)
    t = tag(key, canonical(dst, src, ctr, cmd, args))
    return "%s %d %s%s %s" % (PROTO, ctr, cmd, " " + args if args else "", t)


# ---------------------------------------------------------------------------
# reply
# ---------------------------------------------------------------------------

def reply_canonical(dst: str, src: str, ctr: int, result: str) -> str:
    """Canonical string a reply tag is computed over (dst = managed node)."""
    return "%sR|%s|%s|%d|%s" % (PROTO, dst, src, ctr, result)


def build_reply(dst: str, src: str, ctr: int, result: str, passwd: str) -> str:
    """Reply DM text as the managed node sends it (used for vectors and tests)."""
    if not (result.startswith("ok ") or result.startswith("err ")):
        raise RmError("result must start with 'ok ' or 'err '")
    t = tag(derive_key(passwd), reply_canonical(dst, src, ctr, result))
    return "%s %d %s %s" % (PROTO, ctr, result, t)


def verify_reply(
    text: str, dst: str, src: str, passwd: str, ctr: Optional[int] = None
) -> Optional[Dict[str, Any]]:
    """Verify a reply DM from the managed node `dst` to the sender `src`.

    Returns {"ctr", "status" ("ok"|"err"), "text" (status/reason), "result"}
    when the tag matches (and `ctr` equals the expected counter, if given),
    otherwise None.
    """
    if not isinstance(text, str):
        return None
    parts = text.strip().split(" ")
    if len(parts) < 4 or parts[0] != PROTO or parts[2] not in ("ok", "err"):
        return None
    if not re.fullmatch(r"0|[1-9][0-9]{0,9}", parts[1]):
        return None
    got_ctr = int(parts[1])
    if got_ctr > CTR_MAX or (ctr is not None and got_ctr != ctr):
        return None
    got_tag = parts[-1]
    if not _TAG_RE.fullmatch(got_tag):
        return None
    result = " ".join(parts[2:-1])
    try:
        key = derive_key(passwd)
    except RmError:
        return None
    want = tag(key, reply_canonical(dst, src, got_ctr, result))
    if not hmac.compare_digest(want, got_tag):
        return None
    return {
        "ctr": got_ctr,
        "status": parts[2],
        "text": " ".join(parts[3:-1]),
        "result": result,
    }


# ---------------------------------------------------------------------------
# vectors (tools/tests/remote_cmd_vectors.json)
# ---------------------------------------------------------------------------

_VECTOR_CMDS = [
    # passwd, dst, src, ctr, cmd, args
    ("secret", "DK5EN-90", "DK5EN-1", 1, "reboot", ""),
    ("secret   ", "DK5EN-90", "DK5EN-1", 2, "status", ""),
    ("abcdefghijklmn", "DK5EN-90", "DK5EN-1", 42, "sendpos", ""),
    ("secret", "DK5EN-90", "DK5EN-1", 0, "sync", ""),
    ("secret", "DK5EN-90", "DK5EN-1", 4294967295, "status", ""),
    ("secret", "DK5EN-90", "DK5EN-1", 43, "setout", "a2 on"),
    ("secret", "DK5EN-90", "DK5EN-1", 51, "setout", "b7 off"),
    ("secret", "DK5EN-90", "DK5EN-1", 44, "txpower", "2"),
    ("secret", "DK5EN-90", "DK5EN-1", 45, "gps", "on"),
    ("secret", "DK5EN-90", "DK5EN-1", 46, "display", "off"),
    ("secret", "DK5EN-90", "DK5EN-1", 47, "sendtrack", ""),
    ("secret", "DK5EN-90", "DK5EN-1", 48, "mesh", "on"),
    ("secret", "DK5EN-90", "DK5EN-1", 49, "gateway", "off"),
    ("secret", "DK5EN-90", "DK5EN-1", 50, "track", "off"),
    ("p@ss w0rd!", "DK5EN-92", "DK5EN-14", 7, "reboot", ""),
    ("secret", "DK5EN-92", "DK5EN-1", 1, "reboot", ""),  # dst binding vs vector 1
    ("secret", "DK5EN-90", "DK5EN-14", 1, "reboot", ""),  # src binding vs vector 1
]

_VECTOR_REPLIES = [
    # passwd, dst (managed node), src (sender), ctr, result
    ("secret", "DK5EN-90", "DK5EN-1", 1, "ok rebooting"),
    ("secret", "DK5EN-90", "DK5EN-1", 44, "err range"),
    ("secret   ", "DK5EN-90", "DK5EN-1", 0, "ok ctr=42 v=4.40a"),
    ("abcdefghijklmn", "DK5EN-92", "DK5EN-14", 2, "ok v=4.40a up=125 bat=87 heap=212 gw=0 mesh=1"),
]


def generate_vectors() -> Dict[str, Any]:
    cmds: List[Dict[str, Any]] = []
    for passwd, dst, src, ctr, cmd, args in _VECTOR_CMDS:
        canon = canonical(dst, src, ctr, cmd, args)
        dm = build_command(dst, src, ctr, cmd, args, passwd)
        cmds.append(
            {
                "passwd": passwd,
                "dst": dst,
                "src": src,
                "ctr": ctr,
                "cmd": cmd,
                "args": args,
                "canonical": canon,
                "key_hex": derive_key(passwd).hex(),
                "tag": dm.rsplit(" ", 1)[1],
                "dm_text": dm,
            }
        )
    replies: List[Dict[str, Any]] = []
    for passwd, dst, src, ctr, result in _VECTOR_REPLIES:
        text = build_reply(dst, src, ctr, result, passwd)
        replies.append(
            {
                "passwd": passwd,
                "dst": dst,
                "src": src,
                "ctr": ctr,
                "result": result,
                "key_hex": derive_key(passwd).hex(),
                "reply_canonical": reply_canonical(dst, src, ctr, result),
                "reply_tag": text.rsplit(" ", 1)[1],
                "reply_text": text,
            }
        )
    return {
        "_note": "Generated by tools/remote_cmd.py --gen-vectors; do not edit by hand.",
        "proto": PROTO,
        "commands": cmds,
        "replies": replies,
    }


# ---------------------------------------------------------------------------
# net console send (sender node, TCP 2323, HMAC login like hmac_connect.py)
# ---------------------------------------------------------------------------

def send_via_console(
    host: str, dst: str, dm_text: str, console_passwd: str, port: int = 2323,
    listen_s: float = 3.0,
) -> str:
    """Send `dm_text` as a DM to `dst` through the net console of `host`.

    Uses the console's user-message form `::{CALL}text`. Returns the console
    output seen for `listen_s` seconds after the send.
    """
    if not _SEND_CALL_RE.fullmatch(dst):
        raise RmError("refusing to send: dst %r is not a call with SSID" % dst)
    if "\n" in dm_text or "\r" in dm_text:
        raise RmError("refusing to send: line break in text")
    s = socket.create_connection((host, port), timeout=10)
    try:
        s.settimeout(5)
        f = s.makefile("r", newline="\n")
        line = f.readline().strip()
        if console_passwd:
            if not line.upper().startswith("NONCE:"):
                raise RmError("unexpected console greeting %r" % line)
            nonce = bytes.fromhex(line.split()[1].strip())
            resp = hmac_sha256(console_passwd.encode(), nonce).hex()
            s.sendall((resp + "\n").encode())
            if f.readline().strip() != "OK":
                raise RmError("console authentication failed")
        out: List[str] = []
        # drain banner
        s.settimeout(1.0)
        try:
            while f.readline():
                pass
        except socket.timeout:
            pass
        s.sendall(("::{%s}%s\r\n" % (dst, dm_text)).encode())
        end = time.monotonic() + listen_s
        s.settimeout(0.5)
        while time.monotonic() < end:
            try:
                data = s.recv(512)
            except socket.timeout:
                continue
            if not data:
                break
            out.append(data.decode(errors="replace"))
        return "".join(out)
    finally:
        s.close()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(
        description="Build/verify RM1 remote-management DMs. Print-only unless --send-host is given."
    )
    ap.add_argument("--dst", help="managed node call incl. SSID, e.g. DK5EN-90")
    ap.add_argument("--src", help="sender call incl. SSID, e.g. DK5EN-1")
    ap.add_argument("--passwd", default=os.environ.get("RM_PASSWD"),
                    help="managed node's node_passwd (or env RM_PASSWD)")
    ap.add_argument("--ctr", type=int, help="counter 1..4294967295 (sync: 0, default)")
    ap.add_argument("--send-host", metavar="IP",
                    help="send as a DM via the net console (2323) of the SENDER node")
    ap.add_argument("--console-passwd", default=None,
                    help="net console password of the sender node (default: --passwd)")
    ap.add_argument("--console-port", type=int, default=2323)
    ap.add_argument("--verify", metavar="TEXT", help="verify a reply DM text and print the result")
    ap.add_argument("--gen-vectors", metavar="PATH",
                    help="write tools/tests/remote_cmd_vectors.json to PATH and exit")
    ap.add_argument("cmd", nargs="?", help="allowlisted command")
    ap.add_argument("args", nargs="*", help="command arguments")
    a = ap.parse_args(argv)

    try:
        if a.gen_vectors:
            with open(a.gen_vectors, "w", encoding="utf-8") as fh:
                json.dump(generate_vectors(), fh, indent=2, ensure_ascii=True)
                fh.write("\n")
            print("wrote %s" % a.gen_vectors)
            return 0

        if not (a.dst and a.src and a.passwd):
            ap.error("--dst, --src and --passwd are required")

        if a.verify is not None:
            r = verify_reply(a.verify, a.dst, a.src, a.passwd, a.ctr)
            if r is None:
                print("INVALID")
                return 1
            print(json.dumps(r))
            return 0

        if not a.cmd:
            ap.error("a command is required")
        cmd_args = " ".join(a.args)
        ctr = a.ctr if a.ctr is not None else (0 if a.cmd == "sync" else None)
        if ctr is None:
            ap.error("--ctr is required")
        text = build_command(a.dst, a.src, ctr, a.cmd, cmd_args, a.passwd)
        print(text)
        if a.send_host:
            out = send_via_console(a.send_host, a.dst, text,
                                   a.console_passwd if a.console_passwd is not None else a.passwd,
                                   a.console_port)
            print("--- console output ---")
            print(out)
        return 0
    except RmError as e:
        print("refused: %s" % e, file=sys.stderr)
        return 2
    except OSError as e:
        print("network error: %s" % e, file=sys.stderr)
        return 3


if __name__ == "__main__":
    sys.exit(main())
