#!/usr/bin/env python3
"""
remote_cmd.py - build and verify RM1 remote-management command DMs (issue #1189).

Reference implementation of the wire format in
docs/concept-open-issues-20261004.md section 6.2. The firmware C++ host test
loads tools/tests/remote_cmd_vectors.json (generated by this file) and must
reproduce every tag.

Wire format:
    command  RM1 <ctr> <cmd>[ <args>] <tag>
    reply    RM1 <ctr> ok <status> <tag>   |   RM1 <ctr> err <reason> <tag>

    K         = SHA-256(passwd with trailing spaces stripped)            32 bytes
    canonical = "RM1|" + dst + "|" + src + "|" + ctr + "|" + cmd[ + " " + args]
    tag       = first 8 bytes of HMAC-SHA256(K, canonical), 16 lower-case hex
    reply tag = same over "RM1R|" + dst + "|" + src + "|" + ctr + "|" + result
                (dst = managed node, src = sender, as in the command)

Usage:
    remote_cmd.py --dst DK5EN-90 --src DK5EN-1 --passwd SECRET --ctr 42 reboot
    remote_cmd.py --dst DK5EN-90 --src DK5EN-1 --passwd SECRET --ctr 43 txpower 2
    remote_cmd.py --dst DK5EN-90 --src DK5EN-1 --passwd SECRET sync
    remote_cmd.py --dst DK5EN-90 --src DK5EN-1 --passwd SECRET --verify "RM1 42 ok rebooting <tag>"

Default is print-only. With --send-host <ip> the DM text is sent through the net
console (TCP 2323) of the SENDER node, as the direct message
`::{<DST>}<dm text>` (the console's user-message form; see
tools/bench/tdeck_harness.py). Never a group, never a broadcast.

Requires: Python 3.8+, stdlib only.
"""

from __future__ import annotations

import argparse
import hashlib
import hmac
import json
import os
import re
import socket
import sys
import time
from typing import Any, Dict, List, Optional

PROTO = "RM1"
CTR_MAX = 0xFFFFFFFF
PASSWD_MAX = 14  # node_passwd is char[15]
ARGS_MAX = 39  # RM_MAX_ARGS in src/remote_cmd.h (RmCmd::args[40])
RESULT_MAX = 108  # RM_MAX_RESULT: "RM1 <10> <108> <16>" is 140 chars, the DM limit
LEGACY_RESULT_MAX = 63  # replies of the first 13 commands stay within this (version skew)
CAP_LEVEL = 2  # "rm=<n>" token of the sync reply
TAG_HEX_LEN = 16  # 8 bytes

# cmd -> argument shape. None = no args, tuple = fixed set of allowed arg strings,
# "int" = single unsigned decimal, "out" = "<a0..a7|b0..b7> <on|off>"
# (MCP23017 pin, the firmware's `--setout` form).
ALLOWLIST: Dict[str, Any] = {
    "reboot": None,
    "status": None,
    "sendpos": None,
    "sendtrack": None,
    "gps": ("on", "off"),
    "track": ("on", "off"),
    "display": ("on", "off"),
    "led": ("on", "off"),
    "gateway": ("on", "off"),
    "mesh": ("on", "off"),
    "txpower": "int",
    "setout": "out",
    "sync": None,
    # extended commands (RM ext W2-A): syntax only, ranges and the strict charset are the
    # executor's job (err range / err text). Capitals are allowed in the args of these shapes only.
    "radio": None,
    "sens": None,
    "txq": None,
    "mbox": None,
    "maxhop": None,
    "name": "name",  # none (read) | free text 1..19 (write)
    "atxt": "atxt",  # none (read) | free text 1..39 (write)
    "pos": "pos",    # none (read) | "<lat> <lon> <alt>" (write)
    "mh": "mh",      # row index 0..999 | callsign with optional SSID
}

# Hard-blocked whatever the tag (6.4). Checked before the allowlist so the
# refusal names the reason.
BLOCKED_CMDS = frozenset(
    {
        "cleanflash", "ota-update", "dfu", "deepsleep", "setcall", "passwd",
        "webpwd", "btcode", "setssid", "setpwd", "wifiset", "updrepo",
        "updchan", "autoupdate", "rm", "remotemgmt", "stor", "rmstrictsecurity",
    }
)
BLOCKED_CHARS = ("--", ";", "{", "%")

_INT_RE = re.compile(r"^(0|[1-9][0-9]{0,2})$")
_OUT_RE = re.compile(r"[ab][0-7] (on|off)")
_CALL_RE = re.compile(r"^[A-Z0-9/]{2,12}(-[0-9]{1,2})?$")   # upper case: the node binds its configured call
_SEND_CALL_RE = re.compile(r"^[A-Z0-9/]{2,12}-[0-9]{1,2}$")
_ROW_RE = re.compile(r"[0-9]{1,3}")
_COORD = r"-?[0-9]{1,3}(\.[0-9]{1,6})?"
_POS_RE = re.compile(_COORD + " " + _COORD + " [0-9]{1,5}")
_MHCALL_RE = re.compile(r"[A-Z0-9]{3,9}|[A-Z0-9]{2,8}-[0-9]{1,2}")  # 3..9 chars total, either case on the wire
_TEXT_BAD = set("{}|:")  # wire-level: '|' is the canonical separator
_TAG_RE = re.compile(r"^[0-9a-f]{16}$")


class RmError(ValueError):
    """A command or reply was refused (allowlist, range or format)."""


# ---------------------------------------------------------------------------
# crypto
# ---------------------------------------------------------------------------

def hmac_sha256(key: bytes, msg: bytes) -> bytes:
    """HMAC-SHA256 (RFC 2104); the one primitive every tag goes through."""
    return hmac.new(key, msg, hashlib.sha256).digest()


def derive_key(passwd: str) -> bytes:
    """K = SHA-256(passwd with trailing spaces stripped), 32 bytes."""
    p = passwd.rstrip(" ")
    if not p:
        raise RmError("empty passwd")
    raw = p.encode("utf-8")
    if len(passwd.rstrip(" ")) > PASSWD_MAX:
        raise RmError("passwd longer than %d characters" % PASSWD_MAX)
    return hashlib.sha256(raw).digest()


def tag(key: bytes, canonical_text: str) -> str:
    """First 8 bytes of HMAC-SHA256(key, canonical_text) as 16 lower-case hex chars."""
    return hmac_sha256(key, canonical_text.encode("utf-8")).hex()[:TAG_HEX_LEN]


# ---------------------------------------------------------------------------
# validation
# ---------------------------------------------------------------------------

def _check_call(name: str, call: str) -> None:
    if not isinstance(call, str) or not _CALL_RE.fullmatch(call):
        raise RmError("bad %s call %r" % (name, call))


def _check_ctr(ctr: int) -> None:
    if isinstance(ctr, bool) or not isinstance(ctr, int):
        raise RmError("ctr must be an integer")
    if ctr < 0 or ctr > CTR_MAX:
        raise RmError("ctr out of range 0..%d" % CTR_MAX)


_MIXED_CASE_SHAPES = ("name", "atxt", "pos", "mh")


def _check_ext_args(cmd: str, shape: str, args: str) -> None:
    """Syntax of the extended shapes (mirrors argsMatch in src/remote_cmd.cpp)."""
    if shape in ("name", "atxt", "pos") and args == "":
        return  # read form
    if shape in ("name", "atxt"):
        limit = 19 if shape == "name" else 39
        if not 1 <= len(args) <= limit or any(c in _TEXT_BAD for c in args):
            raise RmError("%s needs free text of 1..%d characters without { } | :" % (cmd, limit))
    elif shape == "pos":
        if not _POS_RE.fullmatch(args):
            raise RmError("pos needs '<lat> <lon> <alt>'")
    elif args.isdigit():  # an all-digit token is a row index only
        if not _ROW_RE.fullmatch(args):
            raise RmError("mh row index is 0..999")
    elif not (len(args) <= 9 and _MHCALL_RE.fullmatch(args.upper())):
        raise RmError("mh needs a row index 0..999 or a callsign")


def validate_command(cmd: str, args: str, ctr: int) -> None:
    """Raise RmError unless (cmd, args, ctr) is an allowlisted RM1 command."""
    _check_ctr(ctr)
    if not isinstance(cmd, str) or not isinstance(args, str):
        raise RmError("cmd and args must be strings")
    text = cmd + (" " + args if args else "")
    for bad in BLOCKED_CHARS:
        if bad in text:
            raise RmError("blocked sequence %r" % bad)
    if len(args) > ARGS_MAX:
        raise RmError("args longer than %d characters" % ARGS_MAX)
    if cmd in BLOCKED_CMDS:
        raise RmError("command %r is hard-blocked" % cmd)
    if not text.isascii() or not text.isprintable():
        raise RmError("non-printable or non-ASCII text")
    if cmd != cmd.lower():
        raise RmError("cmd must be lower case")
    # args stay lower case except where a shape allows capitals (free text, callsign); nothing is case-folded
    if args != args.lower() and ALLOWLIST.get(cmd) not in _MIXED_CASE_SHAPES:
        raise RmError("args must be lower case")
    if "  " in text or text != text.strip():
        raise RmError("single spaces only, no leading/trailing space")
    if cmd not in ALLOWLIST:
        raise RmError("command %r not on the allowlist" % cmd)

    shape = ALLOWLIST[cmd]
    if shape is None:
        if args:
            raise RmError("%s takes no arguments" % cmd)
    elif shape == "int":
        if not _INT_RE.fullmatch(args):
            raise RmError("%s needs one unsigned integer (0..999)" % cmd)
    elif shape == "out":
        if not _OUT_RE.fullmatch(args):
            raise RmError("setout needs '<a0..a7|b0..b7> <on|off>'")
    elif shape in _MIXED_CASE_SHAPES:
        _check_ext_args(cmd, shape, args)
    elif args not in shape:
        raise RmError("%s needs one of %s" % (cmd, "|".join(shape)))

    if cmd == "sync":
        if ctr != 0:
            raise RmError("sync uses ctr 0")
    elif ctr < 1:
        raise RmError("ctr 0 is reserved for sync")


# ---------------------------------------------------------------------------
# command
# ---------------------------------------------------------------------------

def canonical(dst: str, src: str, ctr: int, cmd: str, args: str = "") -> str:
    """Canonical string a command tag is computed over."""
    return "%s|%s|%s|%d|%s%s" % (PROTO, dst, src, ctr, cmd, " " + args if args else "")


def build_command(
    dst: str, src: str, ctr: int, cmd: str, args: str, passwd: str
) -> str:
    """Return the DM text `RM1 <ctr> <cmd>[ <args>] <tag>`; refuse anything off-list."""
    _check_call("dst", dst)
    _check_call("src", src)
    validate_command(cmd, args, ctr)
    key = derive_key(passwd)
    t = tag(key, canonical(dst, src, ctr, cmd, args))
    return "%s %d %s%s %s" % (PROTO, ctr, cmd, " " + args if args else "", t)


# ---------------------------------------------------------------------------
# reply
# ---------------------------------------------------------------------------

def reply_canonical(dst: str, src: str, ctr: int, result: str) -> str:
    """Canonical string a reply tag is computed over (dst = managed node)."""
    return "%sR|%s|%s|%d|%s" % (PROTO, dst, src, ctr, result)


def build_reply(dst: str, src: str, ctr: int, result: str, passwd: str) -> str:
    """Reply DM text as the managed node sends it (used for vectors and tests)."""
    if not (result.startswith("ok ") or result.startswith("err ")):
        raise RmError("result must start with 'ok ' or 'err '")
    if len(result) > RESULT_MAX:
        raise RmError("result longer than %d characters" % RESULT_MAX)
    t = tag(derive_key(passwd), reply_canonical(dst, src, ctr, result))
    return "%s %d %s %s" % (PROTO, ctr, result, t)


def verify_reply(
    text: str, dst: str, src: str, passwd: str, ctr: Optional[int] = None
) -> Optional[Dict[str, Any]]:
    """Verify a reply DM from the managed node `dst` to the sender `src`.

    Returns {"ctr", "status" ("ok"|"err"), "text" (status/reason), "result"}
    when the tag matches (and `ctr` equals the expected counter, if given),
    otherwise None.
    """
    if not isinstance(text, str):
        return None
    parts = text.strip().split(" ")
    if len(parts) < 4 or parts[0] != PROTO or parts[2] not in ("ok", "err"):
        return None
    if not re.fullmatch(r"0|[1-9][0-9]{0,9}", parts[1]):
        return None
    got_ctr = int(parts[1])
    if got_ctr > CTR_MAX or (ctr is not None and got_ctr != ctr):
        return None
    got_tag = parts[-1]
    if not _TAG_RE.fullmatch(got_tag):
        return None
    result = " ".join(parts[2:-1])
    try:
        key = derive_key(passwd)
    except RmError:
        return None
    want = tag(key, reply_canonical(dst, src, got_ctr, result))
    if not hmac.compare_digest(want, got_tag):
        return None
    return {
        "ctr": got_ctr,
        "status": parts[2],
        "text": " ".join(parts[3:-1]),
        "result": result,
    }


# ---------------------------------------------------------------------------
# vectors (tools/tests/remote_cmd_vectors.json)
# ---------------------------------------------------------------------------

_VECTOR_CMDS = [
    # passwd, dst, src, ctr, cmd, args
    ("secret", "DK5EN-90", "DK5EN-1", 1, "reboot", ""),
    ("secret   ", "DK5EN-90", "DK5EN-1", 2, "status", ""),
    ("abcdefghijklmn", "DK5EN-90", "DK5EN-1", 42, "sendpos", ""),
    ("secret", "DK5EN-90", "DK5EN-1", 0, "sync", ""),
    ("secret", "DK5EN-90", "DK5EN-1", 4294967295, "status", ""),
    ("secret", "DK5EN-90", "DK5EN-1", 43, "setout", "a2 on"),
    ("secret", "DK5EN-90", "DK5EN-1", 51, "setout", "b7 off"),
    ("secret", "DK5EN-90", "DK5EN-1", 44, "txpower", "2"),
    ("secret", "DK5EN-90", "DK5EN-1", 45, "gps", "on"),
    ("secret", "DK5EN-90", "DK5EN-1", 46, "display", "off"),
    ("secret", "DK5EN-90", "DK5EN-1", 47, "sendtrack", ""),
    ("secret", "DK5EN-90", "DK5EN-1", 48, "mesh", "on"),
    ("secret", "DK5EN-90", "DK5EN-1", 49, "gateway", "off"),
    ("secret", "DK5EN-90", "DK5EN-1", 50, "track", "off"),
    ("p@ss w0rd!", "DK5EN-92", "DK5EN-14", 7, "reboot", ""),
    ("secret", "DK5EN-92", "DK5EN-1", 1, "reboot", ""),  # dst binding vs vector 1
    ("secret", "DK5EN-90", "DK5EN-14", 1, "reboot", ""),  # src binding vs vector 1
    ("secret", "DK5EN-90", "DK5EN-1", 52, "led", "on"),
    ("secret", "DK5EN-90", "DK5EN-1", 53, "led", "off"),
    # RM ext W2-A: the nine extended names (read and write forms; mh row and call)
    ("secret", "DK5EN-90", "DK5EN-1", 60, "radio", ""),
    ("secret", "DK5EN-90", "DK5EN-1", 61, "sens", ""),
    ("secret", "DK5EN-90", "DK5EN-1", 62, "txq", ""),
    ("secret", "DK5EN-90", "DK5EN-1", 63, "mbox", ""),
    ("secret", "DK5EN-90", "DK5EN-1", 64, "maxhop", ""),
    ("secret", "DK5EN-90", "DK5EN-1", 65, "name", ""),
    ("secret", "DK5EN-90", "DK5EN-1", 66, "name", "Martin"),
    ("secret", "DK5EN-90", "DK5EN-1", 67, "atxt", ""),
    ("secret", "DK5EN-90", "DK5EN-1", 68, "atxt", "MeshCom Garten"),
    ("secret", "DK5EN-90", "DK5EN-1", 69, "pos", ""),
    ("secret", "DK5EN-90", "DK5EN-1", 70, "pos", "48.40812 11.73812 492"),
    ("secret", "DK5EN-90", "DK5EN-1", 71, "mh", "0"),
    ("secret", "DK5EN-90", "DK5EN-1", 72, "mh", "DK5EN-98"),
]

_VECTOR_REPLIES = [
    # passwd, dst (managed node), src (sender), ctr, result
    ("secret", "DK5EN-90", "DK5EN-1", 1, "ok rebooting"),
    ("secret", "DK5EN-90", "DK5EN-1", 44, "err range"),
    ("secret   ", "DK5EN-90", "DK5EN-1", 0, "ok ctr=42 v=4.40a"),
    ("abcdefghijklmn", "DK5EN-92", "DK5EN-14", 2, "ok v=4.40a up=125 bat=87 heap=212 gw=0 mesh=1"),
    # McApp ask 3 (appended, existing entries above never change)
    ("secret", "DK5EN-90", "DK5EN-1", 54, "ok v=4.40a up=417 bat=0 heap=115 s=gtdMwl p=2/22 led=0"),
    ("secret", "DK5EN-90", "DK5EN-1", 55, "ok v=4.40a up=417 bat=87 heap=115 s=GtdmW p=14/22"),
    ("secret", "DK5EN-90", "DK5EN-1", 56, "ok v=4.40A up=71582000 bat=100 heap=199 s=GTDMWL p=22/22 led=1"),
    ("secret", "DK5EN-90", "DK5EN-1", 0, "ok ctr=42 v=4.40a rm=%d" % CAP_LEVEL),
    # RM ext W2-A: worst-case result of every extended formatter (strings of test_rm_format) and the error tokens
    ("secret", "DK5EN-90", "DK5EN-1", 80, "ok f=999.999 sf=99 cr=99 bw=999.99 p=-99/-99"),
    ("secret", "DK5EN-90", "DK5EN-1", 81, "ok t=-99.9 h=100 p=1099.9 t2=-99.9"),
    ("secret", "DK5EN-90", "DK5EN-1", 82, "ok q=65535/65535 bp=qrt tx=4294M rt=4294M dr=4294M u=100"),
    ("secret", "DK5EN-90", "DK5EN-1", 83, "ok m=heard u=65535/65535 b=999999 a=65535/65535 st=4294M dl=4294M ak=4294M dr=4294M bl=4294M nt=4294M"),
    ("secret", "DK5EN-90", "DK5EN-1", 84, "ok t=99 p=99"),
    ("secret", "DK5EN-90", "DK5EN-1", 85, "ok n=NNNNNNNNNNNNNNNNNNN"),
    ("secret", "DK5EN-90", "DK5EN-1", 86, "ok a=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
    ("secret", "DK5EN-90", "DK5EN-1", 87, "ok -89.99999 -179.99999 40000 nofix"),
    ("secret", "DK5EN-90", "DK5EN-1", 4294967294, "ok 999 107 DK5EN-001 180 DK5EN-002 180 DK5EN-003 180 DK5EN-004 180 DK5EN-005 180 DK5EN-006 180 DK5EN-007 180"),
    ("secret", "DK5EN-90", "DK5EN-1", 89, "ok d g=1 m=1 r=-140 s=-20 la=-90.0000 lo=-180.0000 di=9999.9 a=40000 n=255 x=255 h=255 t=65535"),
    ("secret", "DK5EN-90", "DK5EN-1", 90, "ok r h=255 k=255 g=1 m=1 rc=-99.9@DK5EN-001 t=65535 v=DK5EN-001,DK5EN-002,DK5EN-003,DK5EN-004,DK5EN-005"),
    ("secret", "DK5EN-90", "DK5EN-1", 91, "err text"),
    ("secret", "DK5EN-90", "DK5EN-1", 92, "err unknown"),
    ("secret", "DK5EN-90", "DK5EN-1", 93, "err unsupported"),
    ("secret", "DK5EN-90", "DK5EN-1", 94, "err end"),
    ("secret", "DK5EN-90", "DK5EN-1", 95, "err gps"),
    ("secret", "DK5EN-90", "DK5EN-1", 96, "err hidden"),
]


def _status_expect(result: str) -> Optional[Dict[str, Any]]:
    """Fields the firmware's rmStatusParse() must produce (from the format itself)."""
    m = re.search(r" s=([A-Za-z]{5,6}) p=(\d+)/(\d+)( led=[01])?$", result)
    if not result.startswith("ok v=") or m is None:
        return None
    letters = m.group(1)
    sw = [(1 if ch.isupper() else 0) for ch in letters] + [-1] * (6 - len(letters))
    # flat scalars (the native test's JSON reader has no nesting); sw: gps,track,display,mesh,gateway,led
    return {"status_sw": ",".join(("-" if v < 0 else str(v)) for v in sw),
            "status_p": "%s/%s" % (m.group(2), m.group(3)),
            "status_led": len(letters) == 6 or m.group(4) is not None}


def generate_vectors() -> Dict[str, Any]:
    cmds: List[Dict[str, Any]] = []
    for passwd, dst, src, ctr, cmd, args in _VECTOR_CMDS:
        canon = canonical(dst, src, ctr, cmd, args)
        dm = build_command(dst, src, ctr, cmd, args, passwd)
        cmds.append(
            {
                "passwd": passwd,
                "dst": dst,
                "src": src,
                "ctr": ctr,
                "cmd": cmd,
                "args": args,
                "canonical": canon,
                "key_hex": derive_key(passwd).hex(),
                "tag": dm.rsplit(" ", 1)[1],
                "dm_text": dm,
            }
        )
    replies: List[Dict[str, Any]] = []
    for passwd, dst, src, ctr, result in _VECTOR_REPLIES:
        text = build_reply(dst, src, ctr, result, passwd)
        extra: Dict[str, Any] = {}
        st = _status_expect(result)
        if st is not None:
            extra.update(st)
        if result.startswith("ok ctr=") and " rm=" in result:
            extra["cap"] = CAP_LEVEL
        replies.append(
            {**extra,
                "passwd": passwd,
                "dst": dst,
                "src": src,
                "ctr": ctr,
                "result": result,
                "key_hex": derive_key(passwd).hex(),
                "reply_canonical": reply_canonical(dst, src, ctr, result),
                "reply_tag": text.rsplit(" ", 1)[1],
                "reply_text": text,
            }
        )
    return {
        "_note": "Generated by tools/remote_cmd.py --gen-vectors; do not edit by hand.",
        "proto": PROTO,
        "commands": cmds,
        "replies": replies,
    }


# ---------------------------------------------------------------------------
# net console send (sender node, TCP 2323, HMAC login like hmac_connect.py)
# ---------------------------------------------------------------------------

def send_via_console(
    host: str, dst: str, dm_text: str, console_passwd: str, port: int = 2323,
    listen_s: float = 3.0,
) -> str:
    """Send `dm_text` as a DM to `dst` through the net console of `host`.

    Uses the console's user-message form `::{CALL}text`. Returns the console
    output seen for `listen_s` seconds after the send.
    """
    if not _SEND_CALL_RE.fullmatch(dst):
        raise RmError("refusing to send: dst %r is not a call with SSID" % dst)
    if "\n" in dm_text or "\r" in dm_text:
        raise RmError("refusing to send: line break in text")
    s = socket.create_connection((host, port), timeout=10)
    try:
        s.settimeout(5)
        f = s.makefile("r", newline="\n")
        line = f.readline().strip()
        if console_passwd:
            if not line.upper().startswith("NONCE:"):
                raise RmError("unexpected console greeting %r" % line)
            nonce = bytes.fromhex(line.split()[1].strip())
            resp = hmac_sha256(console_passwd.encode(), nonce).hex()
            s.sendall((resp + "\n").encode())
            if f.readline().strip() != "OK":
                raise RmError("console authentication failed")
        out: List[str] = []
        # drain banner
        s.settimeout(1.0)
        try:
            while f.readline():
                pass
        except socket.timeout:
            pass
        s.sendall(("::{%s}%s\r\n" % (dst, dm_text)).encode())
        end = time.monotonic() + listen_s
        s.settimeout(0.5)
        while time.monotonic() < end:
            try:
                data = s.recv(512)
            except socket.timeout:
                continue
            if not data:
                break
            out.append(data.decode(errors="replace"))
        return "".join(out)
    finally:
        s.close()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(
        description="Build/verify RM1 remote-management DMs. Print-only unless --send-host is given."
    )
    ap.add_argument("--dst", help="managed node call incl. SSID, e.g. DK5EN-90")
    ap.add_argument("--src", help="sender call incl. SSID, e.g. DK5EN-1")
    ap.add_argument("--passwd", default=os.environ.get("RM_PASSWD"),
                    help="managed node's node_passwd (or env RM_PASSWD)")
    ap.add_argument("--ctr", type=int, help="counter 1..4294967295 (sync: 0, default)")
    ap.add_argument("--send-host", metavar="IP",
                    help="send as a DM via the net console (2323) of the SENDER node")
    ap.add_argument("--console-passwd", default=None,
                    help="net console password of the sender node (default: --passwd)")
    ap.add_argument("--console-port", type=int, default=2323)
    ap.add_argument("--verify", metavar="TEXT", help="verify a reply DM text and print the result")
    ap.add_argument("--gen-vectors", metavar="PATH",
                    help="write tools/tests/remote_cmd_vectors.json to PATH and exit")
    ap.add_argument("cmd", nargs="?", help="allowlisted command")
    ap.add_argument("args", nargs="*", help="command arguments")
    a = ap.parse_args(argv)

    try:
        if a.gen_vectors:
            with open(a.gen_vectors, "w", encoding="utf-8") as fh:
                json.dump(generate_vectors(), fh, indent=2, ensure_ascii=True)
                fh.write("\n")
            print("wrote %s" % a.gen_vectors)
            return 0

        if not (a.dst and a.src and a.passwd):
            ap.error("--dst, --src and --passwd are required")

        if a.verify is not None:
            r = verify_reply(a.verify, a.dst, a.src, a.passwd, a.ctr)
            if r is None:
                print("INVALID")
                return 1
            print(json.dumps(r))
            return 0

        if not a.cmd:
            ap.error("a command is required")
        cmd_args = " ".join(a.args)
        ctr = a.ctr if a.ctr is not None else (0 if a.cmd == "sync" else None)
        if ctr is None:
            ap.error("--ctr is required")
        text = build_command(a.dst, a.src, ctr, a.cmd, cmd_args, a.passwd)
        print(text)
        if a.send_host:
            out = send_via_console(a.send_host, a.dst, text,
                                   a.console_passwd if a.console_passwd is not None else a.passwd,
                                   a.console_port)
            print("--- console output ---")
            print(out)
        return 0
    except RmError as e:
        print("refused: %s" % e, file=sys.stderr)
        return 2
    except OSError as e:
        print("network error: %s" % e, file=sys.stderr)
        return 3


if __name__ == "__main__":
    sys.exit(main())
